#!/usr/bin/env python3
"""Generate docs/COMMANDS.md from plugin skills and agents. Run: python3 scripts/gen-docs.py  (CI checks it is up to date)."""
import os, re, glob, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def fm(path):
    t = open(path, encoding="utf-8").read()
    m = re.match(r"^---\n(.*?)\n---", t, re.S)
    d = {}
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1); d[k.strip()] = v.strip()
    return d
out = ["# Command & agent reference", "", "_Generated by `scripts/gen-docs.py` — do not edit by hand._", ""]
for pdir in sorted(glob.glob(f"{ROOT}/plugins/*")):
    plugin = os.path.basename(pdir)
    out += [f"## {plugin}", ""]
    agents = sorted(glob.glob(f"{pdir}/agents/*.md"))
    if agents:
        out += ["| Agent | Model | Use for |", "|---|---|---|"]
        for a in agents:
            d = fm(a); out.append(f"| `{d.get('name')}` | {d.get('model','inherit')} | {d.get('description','')} |")
        out.append("")
    cmds, auto = [], []
    for s in sorted(glob.glob(f"{pdir}/skills/*/SKILL.md")):
        d = fm(s); name = d.get("name") or os.path.basename(os.path.dirname(s))
        (cmds if d.get("disable-model-invocation","").lower() in ("true","yes","1","on") else auto).append((name, d.get("description","")))
    if cmds:
        out += ["| Command | Purpose |", "|---|---|"] + [f"| `/{plugin}:{n}` | {desc} |" for n, desc in cmds] + [""]
    if auto:
        out += ["| Background skill (applied automatically) | When |", "|---|---|"] + [f"| `{n}` | {desc} |" for n, desc in auto] + [""]
    hooks = f"{pdir}/hooks/hooks.json"
    if os.path.exists(hooks):
        out += ["Hooks: see `hooks/hooks.json` and `scripts/*.js`.", ""]
text = "\n".join(out) + "\n"
target = f"{ROOT}/docs/COMMANDS.md"
if "--check" in sys.argv:
    cur = open(target, encoding="utf-8").read() if os.path.exists(target) else ""
    sys.exit(0 if cur == text else (print("docs/COMMANDS.md is out of date — run python3 scripts/gen-docs.py") or 1))
os.makedirs(f"{ROOT}/docs", exist_ok=True); open(target, "w", encoding="utf-8").write(text); print("wrote docs/COMMANDS.md")
